import { Accessibility, BarChart3, BookOpenCheck, ClipboardList, FileText, MessageSquareText, MonitorPlay, RefreshCw, Users } from "lucide-react";
import { ArticleHero, ConfidentialityNote, Eyebrow, LearnNav } from "@/components/learn/LearnShell";

const audiences = [
  ["New users", "Build confidence with the core workflow and explain why each step matters.", "Guided practice and concise reference"],
  ["Experienced users", "Understand what changed and transfer existing knowledge safely.", "Change-focused walkthrough and job aid"],
  ["Administrators", "Configure access, resolve common problems, and support other users.", "Scenario workshop and troubleshooting guide"],
  ["Managers", "Interpret participation, completion, and performance without learning every control.", "Role-based overview and reporting guide"],
];

const evidence = [
  ["Performance evidence", "Where do users make errors, abandon a task, or request help?"],
  ["Stakeholder interviews", "What must people do differently after training, and what creates risk?"],
  ["Existing materials", "Which content is accurate, duplicated, missing, outdated, or difficult to retrieve?"],
  ["Learner context", "What do users already know, what constraints affect practice, and when will they apply the skill?"],
];

export default function EnterpriseSystemTraining() {
  return <div className="case-study min-h-screen text-[var(--fg)]"><LearnNav article/><main>
    <ArticleHero category="Instructional design case study" readTime="12 min" title="Designing Training for a Complex Enterprise System" intro="Enterprise software training succeeds when people can perform the right task in the real system—not when every feature has been explained. This case study shows how needs analysis, measurable objectives, practice, accessibility, and evidence shaped a role-based learning strategy."/>

    <section className="case-band border-y border-[var(--hairline)] px-5 py-16 sm:px-6 sm:py-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><Eyebrow>The context</Eyebrow><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">One platform served people with very different responsibilities.</h2><p className="mt-6 leading-7 text-[var(--muted)]">The representative platform combined authentication, personalized content, progress tracking, challenges, notifications, and administrative reporting. A feature-by-feature tour would have overwhelmed new users while giving administrators too little practice with the decisions they owned.</p><p className="mt-4 leading-7 text-[var(--muted)]">The instructional problem was therefore not “How do we explain the application?” It was “What must each audience be able to do, under what conditions, and with what level of support?”</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><Users className="text-[var(--accent)]"/><h3 className="mt-5 font-semibold">Multiple roles</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Learners, administrators, managers, and support specialists entered with different goals and system permissions.</p></div><div className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><MonitorPlay className="text-[var(--accent)]"/><h3 className="mt-5 font-semibold">Multiple moments of need</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Some knowledge belonged in structured training; other information needed to be searchable during work.</p></div></div></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[var(--accent)]"><ClipboardList/><Eyebrow>Needs analysis</Eyebrow></div><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">Investigate the performance gap before prescribing content.</h2><p className="mt-6 max-w-4xl leading-7 text-[var(--muted)]">A request for training may point to a knowledge gap, but it can also reveal unclear workflow design, inconsistent access, missing feedback, outdated documentation, or a process that asks users to remember too much. The analysis combined qualitative input with observable evidence.</p><div className="mt-10 grid gap-4 md:grid-cols-2">{evidence.map(([t,d])=><article key={t} className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><h3 className="font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{d}</p></article>)}</div><div className="mt-8 rounded-2xl border border-[var(--accent)]/30 bg-[var(--accent)]/8 p-6"><p className="text-sm leading-7 text-[var(--muted)]"><b className="text-[var(--fg)]">Decision rule:</b> use training when practice and feedback can close the gap. Correct the interface, permissions, process, or documentation when the barrier is not a lack of knowledge or skill.</p></div></div></section>

    <section className="print-section case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><Eyebrow>Audience strategy</Eyebrow><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">Target the work, not a generic “user.”</h2><div className="mt-10 overflow-hidden rounded-3xl border border-[var(--hairline)] bg-[var(--case-card)]"><div className="hidden grid-cols-[.7fr_1.3fr_1fr] border-b border-[var(--hairline)] bg-[var(--accent)]/8 px-6 py-4 text-xs font-bold uppercase tracking-[.12em] text-[var(--accent)] md:grid"><span>Audience</span><span>Performance need</span><span>Best support</span></div>{audiences.map(([role,need,support])=><article key={role} className="grid gap-3 border-b border-[var(--hairline)] p-6 last:border-0 md:grid-cols-[.7fr_1.3fr_1fr]"><h3 className="font-semibold">{role}</h3><p className="text-sm leading-6 text-[var(--muted)]">{need}</p><p className="text-sm leading-6 text-[var(--muted)]">{support}</p></article>)}</div></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><div className="flex items-center gap-3 text-[var(--accent)]"><BookOpenCheck/><Eyebrow>Learning objectives</Eyebrow></div><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">Write objectives that reveal the assessment.</h2><p className="mt-6 leading-7 text-[var(--muted)]">“Understand the portal” cannot guide content, practice, or evaluation. A measurable objective names the audience, observable performance, relevant conditions, and acceptable standard.</p></div><div className="space-y-4"><div className="rounded-2xl border border-rose-500/25 bg-rose-500/7 p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-rose-600 dark:text-rose-300">Too broad</p><p className="mt-3 text-lg font-semibold">Understand how to manage learner progress.</p></div><div className="rounded-2xl border border-emerald-500/25 bg-emerald-500/7 p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-600 dark:text-emerald-300">Performance based</p><p className="mt-3 text-lg font-semibold">Given an assigned learner and a reported access issue, locate the learner’s current status, identify the blocking requirement, and select the appropriate support action without changing valid completion history.</p></div></div></div></section>

    <section className="case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><Eyebrow>Instructional strategy</Eyebrow><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">Match the format to the behavior and moment of need.</h2><div className="mt-10 grid gap-4 lg:grid-cols-3">{[[MonitorPlay,"Guided practice","Introduce the mental model, demonstrate a complete workflow, and let learners practice realistic decisions with feedback."],[FileText,"Job aids","Support infrequent or high-detail tasks at the moment of performance without requiring memorization."],[MessageSquareText,"Facilitated scenarios","Surface judgment, exceptions, and cross-role handoffs that cannot be taught effectively through passive content alone."]].map(([Icon,t,d])=>{const I=Icon as typeof MonitorPlay;return <article key={t as string} className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><I className="text-[var(--accent)]"/><h3 className="mt-6 text-xl font-semibold">{t as string}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{d as string}</p></article>})}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><div><h3 className="text-lg font-semibold">Adult-learning decisions</h3><ul className="mt-4 space-y-3 text-sm leading-6 text-[var(--muted)]"><li>• Begin with a recognizable problem instead of a list of features.</li><li>• Connect new workflows to knowledge experienced users already possess.</li><li>• Give learners meaningful choices and consequences during practice.</li><li>• Keep reference information available after formal training ends.</li></ul></div><div><h3 className="text-lg font-semibold">Content intentionally excluded</h3><ul className="mt-4 space-y-3 text-sm leading-6 text-[var(--muted)]"><li>• Controls the audience cannot access</li><li>• Rare exceptions better handled through searchable support</li><li>• Background architecture that does not change user decisions</li><li>• Duplicate explanation already maintained by an authoritative source</li></ul></div></div></div></section>

    <section className="print-section case-base px-5 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2"><div><div className="flex items-center gap-3 text-[var(--accent)]"><Accessibility/><Eyebrow>Accessibility and inclusion</Eyebrow></div><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">Access is part of instructional effectiveness.</h2><p className="mt-6 leading-7 text-[var(--muted)]">Materials used semantic structure, keyboard-operable interactions, visible focus, sufficient contrast, descriptive labels, captions or transcripts, and alternatives to color-only meaning. Manual keyboard and screen-reader review complemented automated checks.</p><p className="mt-4 leading-7 text-[var(--muted)]">Localization planning also protected layouts from text expansion and separated translatable language from functional identifiers or code.</p></div><div><Eyebrow>Collaboration model</Eyebrow><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">Review the right question with the right expert.</h2><dl className="mt-6 space-y-4 text-sm leading-6 text-[var(--muted)]"><div><dt className="font-semibold text-[var(--fg)]">Subject-matter experts</dt><dd>Validate process accuracy, exceptions, terminology, and risk.</dd></div><div><dt className="font-semibold text-[var(--fg)]">Product and engineering</dt><dd>Confirm system behavior, permissions, release timing, and technical constraints.</dd></div><div><dt className="font-semibold text-[var(--fg)]">UX and accessibility</dt><dd>Review interaction, readability, focus behavior, and equivalent access.</dd></div><div><dt className="font-semibold text-[var(--fg)]">QA and representative users</dt><dd>Test instructions against the actual workflow and reveal missing assumptions.</dd></div></dl></div></div></section>

    <section className="case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[var(--accent)]"><BarChart3/><Eyebrow>Evaluation</Eyebrow></div><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">Measure whether people can perform—not whether content exists.</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[["Participation","Who began, completed, or returned to the experience?"],["Learning","Can learners demonstrate the defined behavior in assessment or practice?"],["Performance","Do support requests, errors, or completion times change after training?"],["Experience","What feedback reveals unclear language, missing examples, or accessibility barriers?"]].map(([t,d])=><article key={t} className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><h3 className="font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{d}</p></article>)}</div><p className="mt-8 max-w-4xl leading-7 text-[var(--muted)]">Completion is a useful operational signal, not proof of capability. Strong evaluation combines activity data with assessment evidence, performance indicators, learner feedback, and stakeholder observation.</p></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><div className="flex items-center gap-3 text-[var(--accent)]"><RefreshCw/><Eyebrow>Content governance</Eyebrow></div><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">Treat training as a maintained product.</h2><p className="mt-6 leading-7 text-[var(--muted)]">Every asset needs an audience, owner, source of truth, review date, version, and retirement condition. Content should be updated with the product—not rediscovered after learners report that instructions no longer match the interface.</p></div><div className="rounded-3xl border border-[var(--hairline)] bg-[var(--case-card)] p-7"><h3 className="text-lg font-semibold">Release-to-learning loop</h3><div className="mt-6 flex flex-wrap items-center gap-3 text-sm text-[var(--muted)]"><span className="rounded-full border border-[var(--hairline)] px-3 py-2">Product change</span><span>→</span><span className="rounded-full border border-[var(--hairline)] px-3 py-2">Impact review</span><span>→</span><span className="rounded-full border border-[var(--hairline)] px-3 py-2">Content update</span><span>→</span><span className="rounded-full border border-[var(--hairline)] px-3 py-2">Validation</span><span>→</span><span className="rounded-full border border-[var(--hairline)] px-3 py-2">Publish</span><span>→</span><span className="rounded-full border border-[var(--hairline)] px-3 py-2">Feedback</span></div></div></div></section>

    <section className="print-section case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><Eyebrow>Senior takeaway</Eyebrow><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">The deliverable is a performance system, not a pile of courses.</h2><p className="mt-6 max-w-4xl leading-7 text-[var(--muted)]">A mature training solution connects business goals, audience needs, measurable behavior, realistic practice, accessible delivery, searchable support, maintained content, and evidence for improvement. The instructional designer’s role is to make those relationships explicit and keep them aligned as the system changes.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["Role-based learning paths","Facilitator and learner materials","Contextual job aids","LMS organization and metadata","Evaluation plan and reporting definitions","Ownership and maintenance model"].map(x=><div key={x} className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-5 text-sm text-[var(--muted)]">{x}</div>)}</div><div className="mt-14"><ConfidentialityNote/></div></div></section>
  </main></div>;
}
