import Link from "next/link";
import { ArrowRight, Clock } from "lucide-react";
import { LearnNav } from "@/components/learn/LearnShell";
import { learnArticles } from "@/data/learn";

const categories = ["Case Studies", "Tutorials", "Technical Guides", "Visual Explainers"];

export default function LearnPage() {
  return <div className="case-study min-h-screen text-[var(--fg)]"><LearnNav/><main><section className="px-5 pb-16 pt-16 sm:px-6 sm:pb-24 sm:pt-24"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--accent)]">Learn</p><h1 className="mt-5 max-w-5xl text-[clamp(3.2rem,9vw,7rem)] font-semibold leading-[.94] tracking-[-.055em]">Make complex technology<br/><span className="text-[var(--accent)]">useful and understandable.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)] sm:text-xl">A growing collection of case studies, tutorials, technical guides, and visual explainers about the systems I build, the decisions behind them, and the lessons worth sharing.</p><div className="mt-8 flex flex-wrap gap-2">{categories.map(x=><span key={x} className="rounded-full border border-[var(--hairline)] px-3 py-1.5 text-xs text-[var(--muted)]">{x}</span>)}</div></div></section><section className="case-band border-y border-[var(--hairline)] px-5 py-16 sm:px-6 sm:py-24"><div className="mx-auto grid max-w-6xl gap-5 lg:grid-cols-3">{learnArticles.map((article)=><Link key={article.slug} href={`/learn/${article.slug}`} className="group flex min-h-[360px] flex-col rounded-3xl border border-[var(--hairline)] bg-[var(--case-card)] p-6 transition hover:-translate-y-1 hover:border-[var(--accent)]"><div className="flex items-center justify-between"><span className="font-mono text-sm text-[var(--accent)]">{article.number}</span><span className="inline-flex items-center gap-1.5 text-xs text-[var(--muted)]"><Clock size={13}/>{article.readTime}</span></div><div className="mt-auto"><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--accent)]">{article.category}</p><h2 className="mt-4 text-2xl font-semibold leading-tight">{article.title}</h2><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{article.summary}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold group-hover:text-[var(--accent)]">Open article <ArrowRight size={15}/></span></div></Link>)}</div></section></main></div>;
}
