import Link from "next/link";
import { ArrowLeft, ExternalLink, Github, Code2, Layers3, ShieldCheck, TestTube2 } from "lucide-react";

const live = "https://dgutensohn03.github.io/dotnet-insurance-dashboard";
const repo = "https://github.com/dgutensohn03/dotnet-insurance-dashboard";

function Code({ title, lang = "C#", children }: { title: string; lang?: string; children: React.ReactNode }) {
  return <div className="overflow-hidden rounded-2xl border border-white/10 bg-[#0d1117] shadow-xl"><div className="flex items-center justify-between border-b border-white/10 bg-[#161b22] px-4 py-3"><div className="flex gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-[#ff5f57]"/><i className="h-2.5 w-2.5 rounded-full bg-[#febc2e]"/><i className="h-2.5 w-2.5 rounded-full bg-[#28c840]"/></div><span className="font-mono text-[10px] text-slate-400">{title}</span><span className="font-mono text-[9px] text-slate-500">{lang}</span></div><pre className="overflow-x-auto p-5 font-mono text-xs leading-7 text-[#d4d4d4]"><code>{children}</code></pre></div>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-[var(--accent)]">{title}</p><div className="mt-3 text-sm leading-7 text-[var(--muted)]">{children}</div></div>; }
function Preview({ path = "", title }: { path?: string; title: string }) { return <div className="overflow-hidden rounded-2xl border border-[var(--hairline)] bg-white shadow-2xl shadow-black/10"><div className="border-b border-[var(--hairline)] bg-[var(--case-card)] px-4 py-3 text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Live product · {title}</div><iframe title={title} src={`${live}${path}`} className="h-[560px] w-full border-0" loading="lazy"/></div>; }

const serviceCode = `public interface IInsuranceDataService
{
    Task<IReadOnlyList<Claim>> GetClaimsAsync();
    Task<Claim> UpdateClaimAsync(Claim claim);
    Task<DashboardSummary> GetSummaryAsync();
}`;
const filterCode = `var q = claims.Where(c =>
    !minExposure.HasValue || c.Amount >= minExposure);
q = q.Where(c =>
    !lossFrom.HasValue || c.LossDate >= lossFrom);
return q.OrderByDescending(c => c.Amount);`;
const summaryCode = `var activeClaims = claims.Where(c => !c.IsArchived).ToList();
var exposure = activeClaims
    .Where(c => c.Status != "Closed")
    .Sum(c => c.Amount);
// Loss ratio is intentionally a simplified demo signal.`;
const testCode = `await page.getByRole("button", { name: "Edit claim" }).click();
await page.getByLabel("Exposure").fill("75000");
await page.getByRole("button", { name: "Save changes" }).click();`;

export default function CaseStudy() {
  return <div className="case-study min-h-screen overflow-x-hidden text-[var(--fg)]">
    <header className="sticky top-0 z-50 px-4 py-3"><nav className="glass mx-auto flex max-w-7xl items-center justify-between rounded-2xl px-4 py-3"><Link href="/" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><ArrowLeft size={16}/>Portfolio</Link><div className="flex gap-4"><Link href="/insurance-operations/technical-deep-dive" className="inline-flex items-center gap-2 text-sm text-[var(--accent)]"><Code2 size={16}/>Technical deep dive</Link><a href={repo} target="_blank" rel="noreferrer" className="text-[var(--muted)]" aria-label="View InsureOps source on GitHub"><Github size={18}/></a></div></nav></header>
    <main>
      <section className="case-base px-4 pb-20 pt-16 sm:px-6 sm:pt-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--accent)]">Full-stack engineering case study</p><h1 className="mt-6 max-w-6xl text-[clamp(3rem,9vw,5.8rem)] font-semibold leading-[.96] tracking-[-.05em]">Insurance operations,<span className="block text-[var(--accent)]">designed like a real product.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)]">InsureOps is a fictional insurance operations platform built with C#/.NET 8, Blazor WebAssembly, and ASP.NET Core. The work focuses on credible operational workflows: editable records, recoverable lifecycle actions, derived KPIs, sortable and filterable data, accessibility, and automated verification.</p><div className="mt-8 flex flex-wrap gap-3"><a href={live} target="_blank" rel="noreferrer" className="btn-solid">Explore live product <ExternalLink size={15}/></a><Link href="/insurance-operations/technical-deep-dive" className="btn">Read technical deep dive <Code2 size={15}/></Link></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card title="Stack">C# · .NET 8 · Blazor · ASP.NET Core</Card><Card title="Operations">Policies · claims · customers · analytics</Card><Card title="Quality">xUnit · Playwright · CI/CD</Card><Card title="Domain">Edit · archive · restore · derived metrics</Card></div></div></section>
      <section className="case-band border-y border-[var(--hairline)] px-4 py-20 sm:px-6"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="text-3xl font-semibold sm:text-5xl">Start with the operator.</h2><p className="mt-5 leading-7 text-[var(--muted)]">The product is organized around questions an operations user needs answered quickly: what changed, which records need attention, what is in context, and what action is safe to take next. Tables combine global search with meaningful field filters and sortable column headers.</p></div><Preview title="Operations overview"/></div></section>
      <section className="case-base px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><div className="flex items-center gap-3 text-[var(--accent)]"><Layers3/><span className="text-xs font-bold uppercase tracking-wider">Architecture</span></div><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">One UI, two data implementations.</h2><p className="mt-5 max-w-3xl leading-7 text-[var(--muted)]">Blazor pages depend on a typed service contract. The public portfolio build uses deterministic in-browser demo data; full-stack mode uses an HTTP implementation backed by ASP.NET Core and repositories.</p><div className="mt-8 grid gap-4 lg:grid-cols-2"><Code title="IInsuranceDataService.cs">{serviceCode}</Code><Code title="Claims.razor · derived table state" lang="Razor / C#">{filterCode}</Code></div><div className="mt-6 rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><p className="text-xs font-bold uppercase tracking-wider text-[var(--accent)]">Project structure</p><p className="mt-3 max-w-3xl text-sm leading-7 text-[var(--muted)]">Client pages and services, shared models, API endpoints and repositories, xUnit tests, and Playwright E2E each have a clear responsibility. The technical deep dive follows those boundaries through an edit, refresh, and KPI flow.</p><Link href="/insurance-operations/technical-deep-dive" className="mt-4 inline-flex items-center gap-2 font-semibold text-[var(--accent)]">Explore file structure and code <Code2 size={16}/></Link></div></div></section>
      <section className="case-band border-y border-[var(--hairline)] px-4 py-20 sm:px-6"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="text-3xl font-semibold sm:text-5xl">Follow one claim through the product.</h2><p className="mt-5 leading-7 text-[var(--muted)]">CLM-10482 provides a stable example. An operator can find it, sort and filter the claims book, open details without losing table context, edit operational fields, archive or restore the record, and see derived portfolio information recalculate from changed data.</p></div><Preview title="Claims operations" path="/claims"/></div></section>
      <section className="case-base px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><div className="grid gap-4 lg:grid-cols-3"><Card title="Recoverable lifecycle">Claims and customers archive and restore rather than disappear through a generic hard delete.</Card><Card title="Accessible interaction">Dialogs use semantics, labels, focus entry and return, Escape behavior, and visible focus treatment. This is not presented as a completed WCAG certification.</Card><Card title="Responsive operations">Wide tables scroll within their panels; forms stack; drawers become bottom sheets; filters collapse for smaller screens.</Card></div><div className="mt-10 grid gap-4 lg:grid-cols-2"><Code title="summary calculation">{summaryCode}</Code><Code title="interaction verification" lang="Playwright">{testCode}</Code></div></div></section>
      <section className="case-band border-y border-[var(--hairline)] px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><div className="flex items-center gap-3 text-[var(--accent)]"><TestTube2/><span className="text-xs font-bold uppercase tracking-wider">Quality + delivery</span></div><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">Verify the behavior that carries risk.</h2><p className="mt-5 max-w-3xl leading-7 text-[var(--muted)]">xUnit covers service and domain behavior. Playwright exercises deployed workflows in Chromium and mobile WebKit. GitHub Actions builds, tests, publishes, deploys, then runs browser verification against the public product.</p></div></section>
      <section className="case-base px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><div className="flex items-center gap-3 text-[var(--accent)]"><ShieldCheck/><span className="text-xs font-bold uppercase tracking-wider">Outcome</span></div><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">The evidence is the working system, not invented metrics.</h2><p className="mt-5 max-w-3xl leading-7 text-[var(--muted)]">Because InsureOps is fictional, the case study does not manufacture business impact. It demonstrates product thinking, full-stack boundaries, operational data behavior, recoverable lifecycle design, responsive and accessibility decisions, and automated verification.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/insurance-operations/technical-deep-dive" className="btn-solid">Technical deep dive <Code2 size={15}/></Link><a href={repo} target="_blank" rel="noreferrer" className="btn">View source <Github size={15}/></a></div></div></section>
    </main>
  </div>;
}
