import { AlertTriangle, CheckCircle2, Code2, Database, MonitorCheck, Network, Search, Wrench } from "lucide-react";
import { ArticleHero, ConfidentialityNote, Eyebrow, LearnNav } from "@/components/learn/LearnShell";

const investigation = [
  { icon: MonitorCheck, label: "Experience", question: "Did the expected user action fire?", result: "Yes" },
  { icon: Network, label: "Transport", question: "Did the LRS accept the request?", result: "200 OK" },
  { icon: Database, label: "Storage", question: "Can the statement be retrieved?", result: "Found" },
  { icon: Code2, label: "Rules", question: "Does the query recognize the verb?", result: "No" },
];

export default function MissingCompletion() {
  return <div className="case-study min-h-screen text-[var(--fg)]"><LearnNav article/><main><ArticleHero category="Case Study" readTime="6 min" title="The Case of the Missing Completion" intro="The learner finished. The experience confirmed it. The dashboard still said incomplete. Instead of patching the number, the investigation followed the evidence until its meaning changed."/>
    <section className="case-band border-y border-[var(--hairline)] px-5 py-16 sm:px-6 sm:py-20"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><Eyebrow>The signal</Eyebrow><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">One user. Two realities.</h2><p className="mt-6 leading-7 text-[var(--muted)]">The training experience showed a successful completion, while the reporting dashboard classified the same learner as incomplete. Both interfaces appeared to be working.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-emerald-500/25 bg-emerald-500/8 p-6"><CheckCircle2 className="text-emerald-500"/><p className="mt-8 text-xs font-bold uppercase tracking-[.15em] text-emerald-600 dark:text-emerald-300">Learning experience</p><p className="mt-3 text-2xl font-semibold">Complete</p></div><div className="rounded-3xl border border-amber-500/25 bg-amber-500/8 p-6"><AlertTriangle className="text-amber-500"/><p className="mt-8 text-xs font-bold uppercase tracking-[.15em] text-amber-600 dark:text-amber-300">Analytics dashboard</p><p className="mt-3 text-2xl font-semibold">Incomplete</p></div></div></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[var(--accent)]"><Search/><Eyebrow>Follow the evidence</Eyebrow></div><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">Find the first broken assumption.</h2><div className="mt-10 grid gap-4 lg:grid-cols-4">{investigation.map(({icon:Icon,label,question,result},i)=><article key={label} className={`rounded-2xl border p-5 ${i===3?"border-rose-500/45 bg-rose-500/8":"border-[var(--hairline)] bg-[var(--case-card)]"}`}><div className="flex items-center justify-between"><Icon className={i===3?"text-rose-500":"text-[var(--accent)]"} size={22}/><span className="font-mono text-xs text-[var(--muted)]">0{i+1}</span></div><h3 className="mt-6 font-semibold">{label}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-[var(--muted)]">{question}</p><p className={`mt-5 border-t border-[var(--hairline)] pt-4 font-mono text-sm ${i===3?"text-rose-500":"text-emerald-500"}`}>{result}</p></article>)}</div></div></section>

    <section className="case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2"><div><Eyebrow>Root cause</Eyebrow><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">The event arrived. The definition did not.</h2><p className="mt-6 leading-7 text-[var(--muted)]">The updated learning experience sent a custom <code className="rounded bg-[var(--accent)]/10 px-1.5 py-1 font-mono text-sm text-[var(--accent)]">finished</code> verb. The reporting query recognized only the approved <code className="rounded bg-[var(--accent)]/10 px-1.5 py-1 font-mono text-sm text-[var(--accent)]">completed</code> identifier.</p><p className="mt-4 leading-7 text-[var(--muted)]">The LRS correctly preserved both records. The defect lived in the contract between the producer and the reporting rule.</p></div><div className="rounded-3xl border border-[var(--hairline)] bg-[#0d1117] p-6 text-slate-200 shadow-2xl"><p className="font-mono text-xs text-slate-500">statement comparison</p><div className="mt-6 space-y-5 font-mono text-sm"><div><p className="text-slate-500">Expected</p><p className="mt-2 rounded-xl border border-emerald-400/25 bg-emerald-400/8 p-4 text-emerald-300">.../verbs/completed</p></div><div><p className="text-slate-500">Received</p><p className="mt-2 rounded-xl border border-rose-400/25 bg-rose-400/8 p-4 text-rose-300">.../verbs/finished</p></div></div></div></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[var(--accent)]"><Wrench/><Eyebrow>The repair</Eyebrow></div><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">Restore consistency without rewriting history.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-[var(--hairline)] bg-[var(--hairline)] md:grid-cols-3">{[["01","Correct the source","The experience was aligned to the approved completion verb so new events shared one meaning."],["02","Bridge the release window","A documented reporting mapping included affected historical events without altering source statements."],["03","Prevent recurrence","An integration test verified the verb identifier before the next deployment."]].map(([n,t,d])=><div key={n} className="bg-[var(--case-card)] p-6"><span className="font-mono text-sm text-[var(--accent)]">{n}</span><h3 className="mt-6 text-xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{d}</p></div>)}</div></div></section>

    <section className="case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><Eyebrow>Reusable troubleshooting path</Eyebrow><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["Reproduce with a known test identity.","Inspect the outbound request and response.","Validate the complete statement pattern.","Retrieve the record directly from the LRS.","Trace filters, mappings, identity, and time rules.","Compare the API result with the interface."].map((x,i)=><div key={x} className="flex gap-4 rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-5"><span className="font-mono text-xs text-[var(--accent)]">0{i+1}</span><p className="text-sm leading-6 text-[var(--muted)]">{x}</p></div>)}</div><p className="mt-8 max-w-3xl text-sm leading-6 text-[var(--muted)]"><b className="text-[var(--fg)]">Principle:</b> preserve the source record. Correct the producer when possible, make downstream rules explicit, and treat backfills or replays as controlled data changes.</p><div className="mt-14"><ConfidentialityNote/></div></div></section>
  </main></div>;
}
