import { Accessibility, BookOpenCheck, Database, Eye, Gauge, ShieldCheck, Users } from "lucide-react";
import { ArticleHero, ConfidentialityNote, Eyebrow, LearnNav } from "@/components/learn/LearnShell";

export default function AnalyticsPeopleTrust() {
  return <div className="case-study min-h-screen text-[var(--fg)]"><LearnNav article/><main><ArticleHero category="Case Study" readTime="8 min" title="Designing Analytics People Can Trust" intro="A dashboard can be visually polished and still create doubt. Trust begins when people understand what a measure means, where it came from, how current it is, and what they can safely do next."/>
    <section className="case-band border-y border-[var(--hairline)] px-5 py-16 sm:px-6 sm:py-20"><div className="mx-auto max-w-6xl"><Eyebrow>The trust model</Eyebrow><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">Four questions behind every credible metric.</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[Database,"Source","Where did this number come from?"],[BookOpenCheck,"Definition","What exactly does it include?"],[Gauge,"Freshness","How current is the information?"],[Eye,"Traceability","Can I inspect the underlying evidence?"]].map(([Icon,t,d])=>{const I=Icon as typeof Database;return <div key={t as string} className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><I className="text-[var(--accent)]"/><h3 className="mt-8 text-xl font-semibold">{t as string}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{d as string}</p></div>})}</div></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>The starting point</Eyebrow><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">Define the decision before the dashboard.</h2><p className="mt-6 leading-7 text-[var(--muted)]">Stakeholders often request “completion rate” as if it were self-explanatory. It is not. A useful definition names the eligible population, numerator, denominator, date logic, exclusions, update frequency, and owner.</p></div><div className="rounded-3xl border border-[var(--hairline)] bg-[var(--case-card)] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--accent)]">Metric definition</p><div className="mt-6 grid gap-5 sm:grid-cols-2">{[["Measure","Completion rate"],["Numerator","Eligible learners with an approved completion event"],["Denominator","Eligible learners assigned during the reporting period"],["Exclusions","Withdrawn accounts and approved test identities"],["Freshness","Updated every 15 minutes"],["Owner","Program operations"]].map(([k,v])=><div key={k}><p className="text-xs text-[var(--muted)]">{k}</p><p className="mt-1 text-sm font-medium leading-6">{v}</p></div>)}</div></div></div></section>

    <section className="case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><Eyebrow>Translate evidence into action</Eyebrow><div className="mt-8 overflow-hidden rounded-3xl border border-[var(--hairline)] bg-[var(--case-card)]"><div className="grid gap-px bg-[var(--hairline)] md:grid-cols-4">{[["1","Events","Raw learner activity"],["2","Rules","Approved definitions"],["3","Measures","Consistent calculations"],["4","Decisions","Follow-up and improvement"]].map(([n,t,d])=><div key={n} className="bg-[var(--case-card)] p-6"><span className="font-mono text-xs text-[var(--accent)]">{n}</span><h3 className="mt-4 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{d}</p></div>)}</div><div className="border-t border-[var(--hairline)] p-6 sm:p-8"><p className="max-w-4xl leading-7 text-[var(--muted)]">The service layer is not merely plumbing. It is where event history becomes a business measure. Rules for verbs, identity, grouping, duplicate handling, time zones, and eligibility must remain traceable to the definition shown to users.</p></div></div></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[var(--accent)]"><Users/><Eyebrow>Design for different questions</Eyebrow></div><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">One dataset. Several perspectives.</h2><div className="mt-10 grid gap-4 lg:grid-cols-3">{[["Program leader","Are people completing the experience, and where is follow-up needed?"],["Learning designer","Which topics, interactions, or assessments create difficulty?"],["Support and engineering","Is missing data a user issue, source issue, service issue, or reporting issue?"]].map(([t,d])=><div key={t} className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><h3 className="text-lg font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{d}</p></div>)}</div></div></section>

    <section className="case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2"><div><div className="flex items-center gap-3 text-[var(--accent)]"><Accessibility/><Eyebrow>Accessible by design</Eyebrow></div><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">Clarity cannot depend on vision, color, or a mouse.</h2><p className="mt-6 leading-7 text-[var(--muted)]">Charts need descriptive labels, data alternatives, clear focus behavior, and meaning that survives without color. Filters and drilldowns must be keyboard operable, while reading order should preserve the relationship between a measure and its explanation.</p></div><div className="grid gap-3">{["Semantic headings and regions make the page navigable.","Visible focus and logical order support keyboard users.","Labels and patterns supplement color-coded status.","Tables or summaries provide equivalent access to chart values.","Manual keyboard and screen-reader checks complement automation."].map((x,i)=><div key={x} className="flex items-center gap-4 rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[var(--accent)]/10 font-mono text-xs text-[var(--accent)]">{i+1}</span><p className="text-sm leading-6 text-[var(--muted)]">{x}</p></div>)}</div></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[var(--accent)]"><ShieldCheck/><Eyebrow>What shipped</Eyebrow></div><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">A reporting experience built around explanation.</h2><div className="mt-9 grid gap-px overflow-hidden rounded-3xl border border-[var(--hairline)] bg-[var(--hairline)] md:grid-cols-2">{["Reusable measures for progress, completion, assessment performance, and engagement.","A service layer connecting LRS statements, APIs, cloud functions, and PostgreSQL queries.","Role-aware interfaces that gave different users the detail appropriate to their decisions.","Responsive, accessible components that paired visual summaries with inspectable information.","Operational documentation for metric definitions, validation, troubleshooting, and change control.","A shared language that helped clients, product, UX, QA, and engineering evaluate the same evidence."].map((x)=><div key={x} className="bg-[var(--case-card)] p-6 text-sm leading-6 text-[var(--muted)]">{x}</div>)}</div><p className="mt-9 max-w-3xl leading-7 text-[var(--muted)]">The outcome was not simply a set of charts. It was a clearer relationship between what learners did, what the system recorded, what the organization measured, and what people could do with that information.</p><div className="mt-14"><ConfidentialityNote/></div></div></section>
  </main></div>;
}
