import { Activity, ArrowRight, BarChart3, Braces, Database, Gauge, ShieldCheck } from "lucide-react";
import { ArticleHero, ConfidentialityNote, Eyebrow, LearnNav } from "@/components/learn/LearnShell";

const flow = [
  { icon: Activity, label: "Experience", detail: "A meaningful action occurs" },
  { icon: Braces, label: "xAPI statement", detail: "The action becomes structured data" },
  { icon: Database, label: "LRS", detail: "The record is validated and stored" },
  { icon: Gauge, label: "Service layer", detail: "Rules turn events into measures" },
  { icon: BarChart3, label: "Dashboard", detail: "People can interpret and act" },
];

export default function ActivityToInsight() {
  return <div className="case-study min-h-screen text-[var(--fg)]"><LearnNav article/><main><ArticleHero category="Tutorial" readTime="7 min" title="From Activity to Insight" intro="A learner clicks Complete. A dashboard updates. Between those moments, several systems have to agree on what happened, who did it, and what the event means."/>
    <section className="case-band border-y border-[var(--hairline)] px-5 py-16 sm:px-6 sm:py-20"><div className="mx-auto max-w-6xl"><Eyebrow>The complete path</Eyebrow><div className="mt-8 grid gap-3 lg:grid-cols-5">{flow.map(({icon:Icon,label,detail},i)=><div key={label} className="relative rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-5"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[var(--accent)]/10 text-[var(--accent)]"><Icon size={21}/></span>{i<flow.length-1&&<ArrowRight className="hidden text-[var(--accent)]/55 lg:block" size={18}/>}</div><p className="mt-6 font-semibold">{label}</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{detail}</p></div>)}</div><p className="mt-6 max-w-3xl text-sm leading-6 text-[var(--muted)]">A dashboard is not reading a learner’s intent. It is interpreting a chain of technical evidence. Trust depends on every stage preserving the meaning of the original event.</p></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>Start with meaning</Eyebrow><h2 className="mt-5 text-3xl font-semibold leading-tight sm:text-5xl">Capture decisions, not noise.</h2><p className="mt-6 leading-7 text-[var(--muted)]">xAPI can describe almost any experience, but more data is not automatically better data. Begin with the question a person needs answered, then identify the smallest set of events that can answer it reliably.</p><div className="mt-7 space-y-3 text-sm text-[var(--muted)]"><p><b className="text-[var(--fg)]">Question:</b> Who completed the required experience?</p><p><b className="text-[var(--fg)]">Evidence:</b> A completion event connected to a stable learner, activity, and registration.</p><p><b className="text-[var(--fg)]">Decision:</b> Follow up with learners who have not produced that evidence.</p></div></div><div className="overflow-hidden rounded-3xl border border-[var(--hairline)] bg-[#0d1117] shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 bg-[#161b22] px-5 py-4"><span className="font-mono text-xs text-slate-400">completion.statement.json</span><span className="rounded-full bg-emerald-400/10 px-2 py-1 font-mono text-[10px] text-emerald-300">VALID</span></div><pre className="overflow-x-auto p-6 font-mono text-xs leading-7 text-slate-300"><code>{`{
  "actor": { "account": { "name": "learner-482" } },
  "verb": {
    "id": "http://adlnet.gov/expapi/verbs/completed"
  },
  "object": {
    "id": "https://example.org/activity/safety-101"
  },
  "result": { "success": true, "score": { "scaled": 0.92 } },
  "context": { "registration": "7b5f..." },
  "timestamp": "2026-09-21T14:30:00Z"
}`}</code></pre></div></div></section>

    <section className="case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><Eyebrow>Anatomy of the record</Eyebrow><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">Each field answers a different question.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-3xl border border-[var(--hairline)] bg-[var(--hairline)] sm:grid-cols-2 lg:grid-cols-3">{[["Actor","Who performed the action?"],["Verb","What meaningful action occurred?"],["Object","What activity or resource was involved?"],["Result","Was it successful, and was there a score?"],["Context","Which course, module, team, or registration?"],["Timestamp","When did the experience occur?"]].map(([k,v])=><div key={k} className="bg-[var(--case-card)] p-6"><p className="font-mono text-sm text-[var(--accent)]">{k}</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{v}</p></div>)}</div></div></section>

    <section className="case-base px-5 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2"><div><Eyebrow>Where trust breaks</Eyebrow><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">Similar words can create different data.</h2><p className="mt-6 leading-7 text-[var(--muted)]">If three applications represent completion with three unrelated verb identifiers, a query for one identifier will undercount learners. The labels may look equivalent to a person while remaining unrelated to the system.</p></div><div className="rounded-3xl border border-[var(--hairline)] bg-[var(--case-card)] p-6"><div className="space-y-3">{[["completed","Approved","bg-emerald-500/10 text-emerald-600 dark:text-emerald-300"],["finished","Unmapped","bg-amber-500/10 text-amber-600 dark:text-amber-300"],["course_done","Custom","bg-rose-500/10 text-rose-600 dark:text-rose-300"]].map(([verb,state,style])=><div key={verb} className="flex items-center justify-between rounded-xl border border-[var(--hairline)] p-4"><span className="font-mono text-sm">{verb}</span><span className={`rounded-full px-2.5 py-1 text-xs ${style}`}>{state}</span></div>)}</div><p className="mt-5 text-sm leading-6 text-[var(--muted)]">Correct the producer when possible. If a temporary downstream mapping is necessary, document its scope, tests, owner, and retirement plan.</p></div></div></section>

    <section className="case-band border-y border-[var(--hairline)] px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3 text-[var(--accent)]"><ShieldCheck/><Eyebrow>Release checklist</Eyebrow></div><h2 className="mt-5 max-w-4xl text-3xl font-semibold sm:text-5xl">Test the path, not just the request.</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["The intended action triggers one statement.","The statement uses approved identifiers.","The correct LRS accepts and returns it.","Identity and registration remain stable.","Transformation rules match the metric definition.","The dashboard updates within its freshness window."].map((x,i)=><div key={x} className="rounded-2xl border border-[var(--hairline)] bg-[var(--case-card)] p-5"><span className="font-mono text-xs text-[var(--accent)]">0{i+1}</span><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{x}</p></div>)}</div><div className="mt-14"><ConfidentialityNote/></div></div></section>
  </main></div>;
}
